=== kroell/hsrm-mi-2semester-markuplanguage/Abgabe2/Aufgabe1/bestellungDTD.dtd
<!ELEMENT Bestellung (Datum, Adresse, Positionen)>
	<!ELEMENT Datum (#PCDATA)>
	
	<!ELEMENT Adresse (Name, Strasse, PLZ, Ort, Erstbesteller)>
		<!ELEMENT Name (#PCDATA)>
		<!ELEMENT Strasse (#PCDATA)>
		<!ELEMENT PLZ (#PCDATA)>
		<!ELEMENT Ort (#PCDATA)>
		<!ELEMENT Erstbesteller (#PCDATA)>
	
	<!ELEMENT Positionen (Bestellposition*)>
		<!ELEMENT Bestellposition (Artikel|Dienstleistung)>
			<!ELEMENT Artikel (Bestellnummer+, Anzahl+)>
				<!ELEMENT Bestellnummer (#PCDATA)>
				<!ELEMENT Anzahl (#PCDATA)>
			<!ELEMENT Dienstleistung (Bestellnummer+, Anzahl+)>

=== kroell/hsrm-mi-2semester-markuplanguage/Abgabe2/Aufgabe1/bestellung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bestellung SYSTEM "bestellungDTD.dtd">

<Bestellung>
	<Datum>2011-05-05</Datum>
	<Adresse>
		<Name>Max Mustermann</Name>
		<Strasse>Beispielgasse 12</Strasse>
		<PLZ>12345</PLZ>
		<Ort>Musterhausen</Ort>
		<Erstbesteller>true</Erstbesteller>
	      </Adresse>
	<Positionen>
		<Bestellposition>
			<Artikel>
				<Bestellnummer>R305-GK-12</Bestellnummer>
				<Anzahl>5</Anzahl>
			</Artikel>
		</Bestellposition>
		<Bestellposition>
			<Dienstleistung>
				<Bestellnummer>R386-RU-57</Bestellnummer>
				<Anzahl>2</Anzahl>
			</Dienstleistung>
		</Bestellposition>
	</Positionen>
</Bestellung>
