=== kroell/hsrm-mi-2semester-markuplanguage/Praktikumsaufgaben/Blatt 4 Aufgabe 1 DTD/katalog.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT katalog (metadaten?, artikel*)>
<!ELEMENT metadaten (katalogname, firmenname)>
<!ELEMENT katalogname (#PCDATA)>
<!ELEMENT firmenname (#PCDATA)>
<!ELEMENT artikel (bezeichnung,artikel-nr,hersteller*,eigenschaften,preis)>
<!ELEMENT bezeichnung (#PCDATA)>
<!ELEMENT artikel-nr (#PCDATA)>
<!ELEMENT hersteller (firma, land)>
<!ELEMENT firma (#PCDATA)>
<!ELEMENT land (#PCDATA)>
<!ELEMENT eigenschaften EMPTY>
<!ATTLIST eigenschaften
	farbe CDATA #REQUIRED
	groesse CDATA #REQUIRED
>
<!ELEMENT preis (#PCDATA)>
<!ATTLIST preis
	waehrung CDATA #REQUIRED
>

=== kroell/hsrm-mi-2semester-markuplanguage/Praktikumsaufgaben/Blatt 4 Aufgabe 1 DTD/katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE katalog SYSTEM "katalog.dtd">

<katalog>
	<metadaten>
		<katalogname>Mode-Katalog</katalogname>
		<firmenname>Fasion Online</firmenname>
	</metadaten>
	<artikel>
		<bezeichnung>Shirt</bezeichnung>
		<artikel-nr>ab-0001</artikel-nr>
		<hersteller>
			<firma>Tom Taiylor</firma>
			<land>Deutschland</land>
		</hersteller>
		<eigenschaften farbe="schwarz" groesse="S"/>
		<preis waehrung="EUR">19.90</preis>
	</artikel>
	<artikel>
		<bezeichnung>Shirt</bezeichnung>
		<artikel-nr>ab-0002</artikel-nr>
		<hersteller>
			<firma>Hilfanger</firma>
			<land>USA</land>
		</hersteller>
		<eigenschaften farbe="schwarz" groesse="M"/>
		<preis waehrung="USD">54.80</preis>
	</artikel>
	<artikel>
		<bezeichnung>Hose</bezeichnung>
		<artikel-nr>cd-0011</artikel-nr>
		<hersteller>
			<firma>Bose</firma>
			<land>Deutschland</land>
		</hersteller>
		<eigenschaften farbe="blau" groesse="XL"/>
		<preis waehrung="EUR">80.00</preis>
	</artikel>
	<artikel>
		<bezeichnung>Hose</bezeichnung>
		<artikel-nr>fg-0020</artikel-nr>
		<hersteller>
			<firma>Lovis</firma>
			<land>USA</land>
		</hersteller>
		<eigenschaften farbe="schwarz" groesse="L"/>
		<preis waehrung="USD">49.95</preis>
	</artikel>
	<artikel>
		<bezeichnung>Pullover</bezeichnung>
		<artikel-nr>de-0022</artikel-nr>
		<hersteller>
			<firma>Esprot</firma>
			<land>Deutschland</land>
		</hersteller>
		<eigenschaften farbe="rot" groesse="M"/>
		<preis waehrung="EUR">34.90</preis>
	</artikel>
	<artikel>
		<bezeichnung>Pullover</bezeichnung>
		<artikel-nr>xy-0017</artikel-nr>
		<eigenschaften farbe="rot" groesse="M"/>
		<preis waehrung="EUR">19.90</preis>
	</artikel>
	<artikel>
		<bezeichnung>Socken</bezeichnung>
		<artikel-nr>de-0015</artikel-nr>
		<hersteller>
			<firma>Airasis</firma>
			<land>Schweiz</land>
		</hersteller>
		<eigenschaften farbe="weiss" groesse="S"/>
		<preis waehrung="CHF">3.90</preis>
	</artikel>
</katalog>
